---
# tasks file for ansible-role-k3s

- name: get k3s bin
  get_url:
    url: https://get.k3s.io
    dest: /tmp/k3s.sh

- name: Install k3s server
  command: sh /tmp/k3s.sh --docker
  when: ( mode == "server" )

- name: Copy node token into nfs folder
  command: cp /var/lib/rancher/k3s/server/node-token /root/node-token
  when: ( mode == "server" )

- name: Link kubectl to /usr/bin/kubectl
  file:
    src: /usr/local/bin/kubectl
    dest: /usr/bin/kubectl
    state: link
  when: ( mode == "server" )

# - name: Synchronization of k3s node token
#   synchronize:
#     src: /var/lib/rancher/k3s/server/node-token
#     dest: /tmp/node-token
#   delegate_to: "{{ inventory_hostname }}"
#   when: ( mode == "node" )

- name: Install k3s node
  shell: K3S_URL=https://{{ master_ip }}:6443 K3S_TOKEN=`cat  /mnt/nfs/node-token` sh /tmp/k3s.sh
  when: ( mode == "node" )